server:
  port: 7070

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka : true
    fetchRegistry : true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

spring:
  cloud:
    gateway:
      dicovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: licensing-service
          uri: lb://licensing-service